Create main map
sandenson/samba-mario-world pull request #23
Opened 2021-06-11 02:25 UTC by sandenson

2021-06-13 19:29 UTC, Manuel-Antunes commented
Mande uma print de como está ficando

2021-06-17 17:23 UTC, Manuel-Antunes requested changes
please, send the levels screenshots to proceed

2021-06-18 01:51 UTC, sandenson commented
> please, send the levels screenshots to proceed

Mate... there's a gif showing everything already.

2021-06-20 17:18 UTC, Manuel-Antunes approved these changes

2021-06-21 02:26 UTC, merged